// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testback.Data;

#nullable disable

namespace testback.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260115181611_AddTipoYFechaRecepcionInventario")]
    partial class AddTipoYFechaRecepcionInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ARL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AptitudArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AptitudEnAltura")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaInicioContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReentrenamiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRetiro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmoContrato")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<string>("FondoPension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCuenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagoLiquidacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableSecundario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TelefonoEmergencia")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VencimientoAptitudAlturas")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("examenIngreso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad")
                        .HasAnnotation("Relational:JsonPropertyName", "cantidad");

                    b.Property<string>("CodigoHerramienta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreHerramienta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movimiento");
                });

            modelBuilder.Entity("RevisionInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Encontrado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoFisico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRevision")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.ToTable("RevisionInventario");
                });

            modelBuilder.Entity("testback.Models.ActaEntregaEpp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaEmpleadoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaResponsableUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ResponsableId");

                    b.ToTable("ActasEntregaEpp");
                });

            modelBuilder.Entity("testback.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtsId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("EmpresaContratista")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EquiposAUtilizar")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("EquiposEmergencia")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPermiso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrabajoARealizar")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AtsId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("testback.Models.Ats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("FirmaSst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peligros")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QueHacer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QueSucede")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableAts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Riesgo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ats");
                });

            modelBuilder.Entity("testback.Models.ComprobacionPrevia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EvaluacionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaEmpleadoBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermisoTrabajoAlturasId")
                        .HasColumnType("int");

                    b.Property<int>("PersonalAutorizadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermisoTrabajoAlturasId");

                    b.ToTable("ComprobacionesPrevias");
                });

            modelBuilder.Entity("testback.Models.Contratista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contratistas");
                });

            modelBuilder.Entity("testback.Models.DocumentoPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Archivo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("documentopermiso");
                });

            modelBuilder.Entity("testback.Models.ElementoEpp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("RequiereEvidencia")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VidaUtilMeses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ElementosEpp");
                });

            modelBuilder.Entity("testback.Models.ElementoEppInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("CantidadTotal")
                        .HasColumnType("int");

                    b.Property<int>("ElementoEppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ElementoEppId");

                    b.ToTable("ElementosEppInventario");
                });

            modelBuilder.Entity("testback.Models.EntregaEpp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActaEntregaEppId")
                        .HasColumnType("int");

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<int>("ElementoEppInventarioId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActaEntregaEppId");

                    b.HasIndex("ElementoEppInventarioId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("EntregasEpp");
                });

            modelBuilder.Entity("testback.Models.EvidenciaEntregaEpp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActaEntregaEppId")
                        .HasColumnType("int");

                    b.Property<int>("EntregaEppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActaEntregaEppId");

                    b.HasIndex("EntregaEppId");

                    b.ToTable("EvidenciasEntregaEpp");
                });

            modelBuilder.Entity("testback.Models.IngresosPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraEntrada")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IngresosPersonal");
                });

            modelBuilder.Entity("testback.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaMantenimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaProximoMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoMantenimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Garantia")
                        .HasColumnType("int");

                    b.Property<string>("Herramienta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("testback.Models.InventarioInterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadAsignada")
                        .HasColumnType("int");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<string>("Obra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usando")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.ToTable("InventarioInterno");
                });

            modelBuilder.Entity("testback.Models.Obra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CostoObra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<string>("ResponsableSecundario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tamano")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCaliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionTarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementosProteccionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("Herramientas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPermiso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeligrosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proyecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoTrabajo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("PermisosEnCaliente");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCalienteAutorizante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermisoEnCalienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PermisoEnCalienteId");

                    b.ToTable("PermisosEnCalienteAutorizantes");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCalienteEvaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EvaluacionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermisoEnCalientePersonalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermisoEnCalientePersonalId");

                    b.ToTable("PermisoEnCalienteEvaluaciones");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCalientePersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("EvaluacionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermisoEnCalienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PermisoEnCalienteId");

                    b.ToTable("PermisosEnCalientePersonal");
                });

            modelBuilder.Entity("testback.Models.PermisoTrabajoAlturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AlturaAproximada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AyudanteSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AyudanteSeguridadEmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("CoordinadorTrabajoAlturas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoordinadorTrabajoAlturasEmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionTarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaFinalizacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<string>("FirmaResponsableBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HerramientaUtilizar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LugarEjecucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedidaPrevencionProteccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtroAcceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtrosElementos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonaAutoriza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonaAutorizaEmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("ProteccionPersonal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsablePermiso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponsablePermisoEmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoTrabajoRealizar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TrabajoElectrico")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AyudanteSeguridadEmpleadoId");

                    b.HasIndex("CoordinadorTrabajoAlturasEmpleadoId");

                    b.HasIndex("PersonaAutorizaEmpleadoId");

                    b.HasIndex("ResponsablePermisoEmpleadoId");

                    b.ToTable("PermisosTrabajoAlturas");
                });

            modelBuilder.Entity("testback.Models.PersonalAutorizado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ActivoSeguridadSocial")
                        .HasColumnType("bit");

                    b.Property<string>("Certificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermisoTrabajoAlturasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PermisoTrabajoAlturasId");

                    b.ToTable("PersonalAutorizado");
                });

            modelBuilder.Entity("testback.Models.RegistroJornada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<double>("HorasDiurnas")
                        .HasColumnType("float");

                    b.Property<double>("HorasDominicales")
                        .HasColumnType("float");

                    b.Property<double>("HorasExtrasDiurnas")
                        .HasColumnType("float");

                    b.Property<double>("HorasExtrasDominicales")
                        .HasColumnType("float");

                    b.Property<double>("HorasExtrasNocturnas")
                        .HasColumnType("float");

                    b.Property<double>("HorasNocturnas")
                        .HasColumnType("float");

                    b.Property<double>("HorasRecargoNocturnoDominical")
                        .HasColumnType("float");

                    b.Property<double>("HorasTrabajadas")
                        .HasColumnType("float");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrabajoDomingo")
                        .HasColumnType("bit");

                    b.Property<bool>("TrabajoFestivo")
                        .HasColumnType("bit");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistroJornada");
                });

            modelBuilder.Entity("testback.Models.Rendimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Actividad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdContratista")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Rendimiento");
                });

            modelBuilder.Entity("testback.Models.ResponsablePlanEmergencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermisoTrabajoAlturasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PermisoTrabajoAlturasId");

                    b.ToTable("ResponsablePlanEmergencia");
                });

            modelBuilder.Entity("testback.Models.SalidasPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SalidasPersonal");
                });

            modelBuilder.Entity("testback.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaSolicitud");

                    b.Property<string>("Obra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("obra");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("solicitante");

                    b.HasKey("Id");

                    b.ToTable("Solicitud");
                });

            modelBuilder.Entity("testback.Models.SolicitudItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int")
                        .HasColumnName("inventarioId");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int")
                        .HasColumnName("solicitudId");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.HasIndex("SolicitudId");

                    b.ToTable("solicitud_item");
                });

            modelBuilder.Entity("testback.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContrasenaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObraId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("RevisionInventario", b =>
                {
                    b.HasOne("testback.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("testback.Models.ActaEntregaEpp", b =>
                {
                    b.HasOne("Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Empleado", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("testback.Models.Actividad", b =>
                {
                    b.HasOne("testback.Models.Ats", "Ats")
                        .WithMany("Actividades")
                        .HasForeignKey("AtsId");

                    b.HasOne("Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ats");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("testback.Models.ComprobacionPrevia", b =>
                {
                    b.HasOne("testback.Models.PermisoTrabajoAlturas", "PermisoTrabajoAlturas")
                        .WithMany("ComprobacionesPrevias")
                        .HasForeignKey("PermisoTrabajoAlturasId");

                    b.Navigation("PermisoTrabajoAlturas");
                });

            modelBuilder.Entity("testback.Models.ElementoEppInventario", b =>
                {
                    b.HasOne("testback.Models.ElementoEpp", "ElementoEpp")
                        .WithMany()
                        .HasForeignKey("ElementoEppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElementoEpp");
                });

            modelBuilder.Entity("testback.Models.EntregaEpp", b =>
                {
                    b.HasOne("testback.Models.ActaEntregaEpp", "ActaEntregaEpp")
                        .WithMany("Entregas")
                        .HasForeignKey("ActaEntregaEppId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("testback.Models.ElementoEppInventario", "ElementoEppInventario")
                        .WithMany()
                        .HasForeignKey("ElementoEppInventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActaEntregaEpp");

                    b.Navigation("ElementoEppInventario");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("testback.Models.EvidenciaEntregaEpp", b =>
                {
                    b.HasOne("testback.Models.ActaEntregaEpp", null)
                        .WithMany("Evidencias")
                        .HasForeignKey("ActaEntregaEppId");

                    b.HasOne("testback.Models.EntregaEpp", "EntregaEpp")
                        .WithMany("EvidenciasEntregaEpp")
                        .HasForeignKey("EntregaEppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntregaEpp");
                });

            modelBuilder.Entity("testback.Models.InventarioInterno", b =>
                {
                    b.HasOne("testback.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("testback.Models.Obra", b =>
                {
                    b.HasOne("testback.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("testback.Models.PermisoEnCaliente", b =>
                {
                    b.HasOne("Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCalienteAutorizante", b =>
                {
                    b.HasOne("Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testback.Models.PermisoEnCaliente", "PermisoEnCaliente")
                        .WithMany("Autorizantes")
                        .HasForeignKey("PermisoEnCalienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("PermisoEnCaliente");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCalienteEvaluacion", b =>
                {
                    b.HasOne("testback.Models.PermisoEnCalientePersonal", "Personal")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("PermisoEnCalientePersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCalientePersonal", b =>
                {
                    b.HasOne("Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testback.Models.PermisoEnCaliente", "PermisoEnCaliente")
                        .WithMany("Personal")
                        .HasForeignKey("PermisoEnCalienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("PermisoEnCaliente");
                });

            modelBuilder.Entity("testback.Models.PermisoTrabajoAlturas", b =>
                {
                    b.HasOne("Empleado", "AyudanteSeguridadEmpleado")
                        .WithMany()
                        .HasForeignKey("AyudanteSeguridadEmpleadoId");

                    b.HasOne("Empleado", "CoordinadorTrabajoAlturasEmpleado")
                        .WithMany()
                        .HasForeignKey("CoordinadorTrabajoAlturasEmpleadoId");

                    b.HasOne("Empleado", "PersonaAutorizaEmpleado")
                        .WithMany()
                        .HasForeignKey("PersonaAutorizaEmpleadoId");

                    b.HasOne("Empleado", "ResponsablePermisoEmpleado")
                        .WithMany()
                        .HasForeignKey("ResponsablePermisoEmpleadoId");

                    b.Navigation("AyudanteSeguridadEmpleado");

                    b.Navigation("CoordinadorTrabajoAlturasEmpleado");

                    b.Navigation("PersonaAutorizaEmpleado");

                    b.Navigation("ResponsablePermisoEmpleado");
                });

            modelBuilder.Entity("testback.Models.PersonalAutorizado", b =>
                {
                    b.HasOne("Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("testback.Models.PermisoTrabajoAlturas", null)
                        .WithMany("PersonalAutorizado")
                        .HasForeignKey("PermisoTrabajoAlturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("testback.Models.ResponsablePlanEmergencia", b =>
                {
                    b.HasOne("Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("testback.Models.PermisoTrabajoAlturas", null)
                        .WithMany("ResponsablesPlanEmergencia")
                        .HasForeignKey("PermisoTrabajoAlturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("testback.Models.SolicitudItem", b =>
                {
                    b.HasOne("testback.Models.Inventario", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testback.Models.Solicitud", "Solicitud")
                        .WithMany("Items")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("testback.Models.ActaEntregaEpp", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("testback.Models.Ats", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("testback.Models.EntregaEpp", b =>
                {
                    b.Navigation("EvidenciasEntregaEpp");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCaliente", b =>
                {
                    b.Navigation("Autorizantes");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("testback.Models.PermisoEnCalientePersonal", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("testback.Models.PermisoTrabajoAlturas", b =>
                {
                    b.Navigation("ComprobacionesPrevias");

                    b.Navigation("PersonalAutorizado");

                    b.Navigation("ResponsablesPlanEmergencia");
                });

            modelBuilder.Entity("testback.Models.Solicitud", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
